Do not hadd if there's only one input file
https://github.com/HEP-KBFI/tth-htt/issues/171

diff --git a/python/templates/sbatch-node.hadd.sh.template b/python/templates/sbatch-node.hadd.sh.template
--- a/python/templates/sbatch-node.hadd.sh.template
+++ b/python/templates/sbatch-node.hadd.sh.template
@@ -180,59 +180,62 @@ run_wrapped_executable() {
     fi
 
     if [[ $EXIT_CODE -ne 0 ]]; then
-	  echo 'ERROR: hadd exited w/ non-zero return code. Will stop execution.'
-	  cleanup "$JOB_DIR"
-	  return $EXIT_CODE
+      echo 'ERROR: hadd exited w/ non-zero return code. Will stop execution.'
+      cleanup "$JOB_DIR"
+      return $EXIT_CODE
     fi
 
     echo "Contents of temporary job dir: ls -laR $JOB_DIR"
     ls -laR $JOB_DIR
 
-    echo "Copying output files: {{ outputFiles }}"
-    for OUTPUT_FILE in $OUTPUT_FILES; do
-      # Check that input histograms are equal to output histogram
-      check_that_histograms_are_equal.py $OUTPUT_FILE $INPUT_FILES
-      EXIT_CODE=$?
+    SKIP_COPY={{ skip_copy }}
+    if [[ $SKIP_COPY -eq 0 ]]; then
+      echo "Copying output files: {{ outputFiles }}"
+      for OUTPUT_FILE in $OUTPUT_FILES; do
+        # Check that input histograms are equal to output histogram
+        check_that_histograms_are_equal.py $OUTPUT_FILE $INPUT_FILES
+        EXIT_CODE=$?
 
-      if [[ $EXIT_CODE -ne 0 ]]; then
-	    echo 'ERROR: Input histograms do not equal output histogram. Will stop execution.'
-	    return 6;
-      fi
-
-      OUTPUT_FILE_SIZE=$(stat -c '%s' $OUTPUT_FILE)
-      if [ -n "$OUTPUT_FILE_SIZE" ] && [ $OUTPUT_FILE_SIZE -ge 1000 ]; then
-        echo "$cp_cmd $OUTPUT_FILE $OUTPUT_DIR/$OUTPUT_FILE"
-
-        CP_RETRIES=0
-        COPIED=false
-        while [ $CP_RETRIES -lt 3 ]; do
-          CP_RETRIES=$[CP_RETRIES + 1];
-          $cp_cmd $OUTPUT_FILE $OUTPUT_DIR/$OUTPUT_FILE
-
-          # add a small delay before stat'ing the file
-          sleep 5s
-
-          REMOTE_SIZE=$($st_cmd $OUTPUT_DIR/$OUTPUT_FILE)
-          if [ "$REMOTE_SIZE" == "$OUTPUT_FILE_SIZE" ]; then
-            COPIED=true
-            break;
-          else
-            continue;
-          fi
-        done
-
-        if [ ! $COPIED ]; then
-          EXIT_CODE=5;
-        else
-          $ls_cmd $OUTPUT_DIR/$OUTPUT_FILE
+        if [[ $EXIT_CODE -ne 0 ]]; then
+        echo 'ERROR: Input histograms do not equal output histogram. Will stop execution.'
+        return 6;
         fi
 
-      else
-        echo "$OUTPUT_FILE is broken, will exit with code 1."
-        rm $OUTPUT_FILE
-        EXIT_CODE=1
-      fi
-    done
+        OUTPUT_FILE_SIZE=$(stat -c '%s' $OUTPUT_FILE)
+        if [ -n "$OUTPUT_FILE_SIZE" ] && [ $OUTPUT_FILE_SIZE -ge 1000 ]; then
+          echo "$cp_cmd $OUTPUT_FILE $OUTPUT_DIR/$OUTPUT_FILE"
+
+          CP_RETRIES=0
+          COPIED=false
+          while [ $CP_RETRIES -lt 3 ]; do
+            CP_RETRIES=$[CP_RETRIES + 1];
+            $cp_cmd $OUTPUT_FILE $OUTPUT_DIR/$OUTPUT_FILE
+
+            # add a small delay before stat'ing the file
+            sleep 5s
+
+            REMOTE_SIZE=$($st_cmd $OUTPUT_DIR/$OUTPUT_FILE)
+            if [ "$REMOTE_SIZE" == "$OUTPUT_FILE_SIZE" ]; then
+              COPIED=true
+              break;
+            else
+              continue;
+            fi
+          done
+
+          if [ ! $COPIED ]; then
+            EXIT_CODE=5;
+          else
+            $ls_cmd $OUTPUT_DIR/$OUTPUT_FILE
+          fi
+
+        else
+          echo "$OUTPUT_FILE is broken, will exit with code 1."
+          rm $OUTPUT_FILE
+          EXIT_CODE=1
+        fi
+      done
+    fi
 
     echo "End time is: `date`"
 
