Propagate I/O and validation errors from hadd jobs to sbatchManager

diff --git a/python/templates/sbatch-node.hadd.sh.template b/python/templates/sbatch-node.hadd.sh.template
--- a/python/templates/sbatch-node.hadd.sh.template
+++ b/python/templates/sbatch-node.hadd.sh.template
@@ -53,6 +53,13 @@ run_failure_wrapped_executable() {
     return $EXIT_CODE
 }
 
+cleanup() {
+    if [ ! -z "$1" ]; then
+        echo "Deleting directory: rm -r $1"
+        rm -r "$1";
+    fi
+}
+
 
 # Creates scratch dir on cluster node or on /home and runs executable
 
@@ -60,8 +67,6 @@ run_wrapped_executable() {
     EXECUTABLE_LOG_FILE="{{ executable_log_file }}"
     EXECUTABLE_LOG_DIR="`dirname $EXECUTABLE_LOG_FILE`"
     EXECUTABLE_LOG_FILE_NAME="`basename $EXECUTABLE_LOG_FILE`"
-    TEMPORARY_EXECUTABLE_LOG_DIR="$JOB_DIR/$EXECUTABLE_LOG_DIR/"
-    TEMPORARY_EXECUTABLE_LOG_FILE="$TEMPORARY_EXECUTABLE_LOG_DIR/$EXECUTABLE_LOG_FILE_NAME"
     RANDOM_SLEEP={{ random_sleep }}
 
     echo "Time is: `date`"
@@ -73,19 +78,22 @@ run_wrapped_executable() {
 
     # Check that input histograms are ok on /home
     export SCRIPTS_DIR="$CMSSW_BASE/src/tthAnalysis/HiggsToTauTau/scripts"
-    python $SCRIPTS_DIR/check_that_histograms_are_valid.py {{ inputFiles }}
-    check_that_histograms_are_valid_exit_status=$?
+    python $SCRIPTS_DIR/check_that_histograms_are_valid.py {{ inputFiles }} &> $EXECUTABLE_LOG_FILE
+    EXIT_CODE=$?
 
-    if [[ $check_that_histograms_are_valid_exit_status -ne 0 ]]; then
-	echo "ERROR: Some of the input histograms are not valid. Will stop execution."
-	return 1
+    IO_GREP=$(grep "SysError in <TFile::ReadBuffer>" $EXECUTABLE_LOG_FILE | grep "(Input/output error)" | wc -l)
+    if [[ $IO_GREP -ne 0 ]]; then
+      echo "Encountered I/O error; setting the exit code accordingly";
+      EXIT_CODE=3;
+    fi
+
+    if [[ $EXIT_CODE -ne 0 ]]; then
+	  echo "ERROR: Some of the input histograms are not valid. Will stop execution.";
+	  return $EXIT_CODE;
     fi
 
     echo "Create job directory: mkdir -p $JOB_DIR"
     mkdir -p $JOB_DIR
-
-    echo "Create temporary log directory: mkdir -p $TEMPORARY_EXECUTABLE_LOG_DIR"
-    mkdir -p $TEMPORARY_EXECUTABLE_LOG_DIR
 
     echo "Create final log directory: mkdir -p $EXECUTABLE_LOG_DIR"
     mkdir -p $EXECUTABLE_LOG_DIR
@@ -96,16 +104,23 @@ run_wrapped_executable() {
 
     CMSSW_SEARCH_PATH="$JOB_DIR:{{ cmssw_base_dir }}/src"
 
-    echo "Execute command: {{ exec_name }} {{ command_line_parameter }} &> $TEMPORARY_EXECUTABLE_LOG_FILE"
-    {{ exec_name }} {{ command_line_parameter }} &> $TEMPORARY_EXECUTABLE_LOG_FILE
+    echo "Execute command: {{ exec_name }} {{ command_line_parameter }} &>> $EXECUTABLE_LOG_FILE"
+    {{ exec_name }} {{ command_line_parameter }} &>> $EXECUTABLE_LOG_FILE
     EXIT_CODE=$?
     echo "Command {{ exec_name }} exited with code $EXIT_CODE"
 
     echo "Time is: `date`"
 
+    IO_GREP=$(grep "SysError in <TFile::ReadBuffer>" $EXECUTABLE_LOG_FILE | grep "(Input/output error)" | wc -l)
+    if [[ $IO_GREP -ne 0 ]]; then
+      echo "Encountered I/O error; setting the exit code accordingly";
+      EXIT_CODE=3;
+    fi
+
     if [[ $EXIT_CODE -ne 0 ]]; then
-	echo 'ERROR: hadd exited w/ non-zero return code. Will stop execution.'
-	return 1
+	  echo 'ERROR: hadd exited w/ non-zero return code. Will stop execution.'
+	  cleanup "$JOB_DIR"
+	  return $EXIT_CODE
     fi
 
     echo "Contents of temporary job dir: ls -laR $JOB_DIR"
@@ -120,11 +135,11 @@ run_wrapped_executable() {
 
       # Check that input histograms are equal to output histogram
       python $CMSSW_BASE/src/tthAnalysis/HiggsToTauTau/scripts/check_that_histograms_are_equal.py $OUTPUT_FILE {{ inputFiles }}
-      CHECK_THAT_HISTOGRAMS_ARE_EQUAL_EXIT_CODE=$?
+      EXIT_CODE=$?
 
-      if [[ $CHECK_THAT_HISTOGRAMS_ARE_EQUAL_EXIT_CODE -ne 0 ]]; then
-	  echo 'ERROR: Input histograms do not equal output histogram. Will stop execution.'
-	  return 1
+      if [[ $EXIT_CODE -ne 0 ]]; then
+	    echo 'ERROR: Input histograms do not equal output histogram. Will stop execution.'
+	    return 6;
       fi
 
       OUTPUT_DIR="{{ outputDir }}"
@@ -165,7 +180,7 @@ run_wrapped_executable() {
         done
 
         if [ ! $COPIED ]; then
-          EXIT_CODE=1;
+          EXIT_CODE=5;
         else
           $ls_cmd $OUTPUT_DIR/$OUTPUT_FILE
         fi
@@ -177,15 +192,9 @@ run_wrapped_executable() {
       fi
     done
 
-    echo "Time is: `date`"
-
-    echo "Contents of temporary log dir: ls -laR $TEMPORARY_EXECUTABLE_LOG_DIR"
-    ls -laR $TEMPORARY_EXECUTABLE_LOG_DIR
-
-    echo "Copy from temporary output dir to output dir: cp -a $TEMPORARY_EXECUTABLE_LOG_DIR/* $EXECUTABLE_LOG_DIR/"
-    cp -a $TEMPORARY_EXECUTABLE_LOG_DIR/* $EXECUTABLE_LOG_DIR/
-
     echo "End time is: `date`"
+
+    cleanup "$JOB_DIR"
 
     echo "Waiting for 10 seconds before returning"
     sleep 10
